### ISSUE TITLE
We need side kicks

### ISSUE THREAD

**Issue by iamakhilk** [iamakhilk/Team-of-Heroes#6]
we need sidekicks, for eg. like Alfred for Batman 
[this is the link ](https://www.google.com)

![image](https://user-images.githubusercontent.com/30595063/41055615-69bb7a8c-69df-11e8-808c-b661547f8364.png)

**Comment by CO16312akhil** [comment]
no its a small project , i think its cool if we leave it like this and also deadline is close we cant afford this addition.
